<!--
WARNING: This file was autogenerated by MagicDraw MBRS plugin.
Do not update it because if you run generator again you changes will be deleted
-->
<!DOCTYPE HTML>
<html>
<head>
    <title>Create ${class.name}</title>
    <style>
        ${r"<#include 'common.css'>"}
    </style>
</head>
<body>
<header>
    <a href="javascript:history.back()">back</a>
    <h2>New ${class.name}</h2>
</header>
<#if class.page?? && class.page.create?c=="true">
    <div class="wrapper">
        <fieldset>
            <legend>New ${class.name}</legend>
            <form name="product" action="${r"${springMacroRequestContext.getContextPath()}"}/${class.name?uncap_first}/add" method="post">
            <#list properties as property>
            <#if property.name != "id">
            <#if property.type.name == "Integer" || property.type.name == "Double">
                ${property.name?cap_first}: <input type="number" name="${property.name}" /><br/>
            <#elseif property.type.name == "String">
                ${property.name?cap_first}: <input type="text" name="${property.name}" /><br/>
            <#elseif property.type.name == "Boolean" >
            ${property.name?cap_first}: <input type="checkbox" name="${property.name}" id="${property.name}">
            <input type="hidden" value="on" name="_${property.name}"/>
            <#elseif property.type.name == "Date" || property.type.name == "date">
                ${property.name?cap_first}: <input type="date" name="${property.name}" id="${property.name}" pattern="[0-9]{4}-[0-9]{2}-[0-9]{2}"/><br />
            <#else>
            </#if>
            </#if>
            </#list>
                <input type="submit" value="Add" />
            </form>
        </fieldset>
        <br/>
    </div>
<#else>
</#if>
</body>
</html>