<!--
WARNING: This file was autogenerated by MagicDraw MBRS plugin.
Do not update it because if you run generator again you changes will be deleted
-->
<!DOCTYPE HTML>
<html>
<head>
    <title>${class.name} Details</title>
    <style>
        ${r"<#include 'common.css'>"}
    </style>
</head>
<body>
<header>
    <a href="/index">home</a>
    <h2>${class.name} Details</h2>
</header>
<#if class.page?? && class.page.details?c=="true">
    <div class="wrapper">
        <table border="1">
            <tr>
                <td>id</td>
                <td>${r"${"}${class.name?uncap_first}.id${r"}"}</td>
            </tr>
            <#list properties as property>
            <tr>
                <td>${property.name}</td>
                <#if property.type.name == "Integer" || property.type.name == "String">
                <td>${r"${"}${class.name?uncap_first}.${property.name}${r"}"}</td>
                <#elseif property.type.name == "Boolean" || property.type.name == "boolean">
                <td>${r"${"}${class.name?uncap_first}.${property.name}?string${r"}"}</td>
                <#elseif property.type.name == "Date" || property.type.name == "date">
                <td>${r"${"}${class.name?uncap_first}.${property.name}?date${r"}"}</td>
                <#else>
                <td>
                    ${r"<#if "}${class.name?uncap_first}.${property.name}${r"?has_content?c=='false'>
                        null"}
                    ${r"<#else>"}
                        ${r"${"}${class.name?uncap_first}.${property.name}.id${r"}"}
                    ${r"</#if>"}
                </td>
                </#if>
            </tr>
            </#list>
            <#if class.page.update?c=="true">
                <tr>
                    <td>Update</td>
                    <td><a href="/${class.name?uncap_first}/update/${r"${"}${class.name?uncap_first}.id${r"}"}">Update ${class.name?uncap_first}</a></td>
                </tr>
            </#if>
            <tr>
                <td>Delete</td>
                <td><a href="/${class.name?uncap_first}/delete/${r"${"}${class.name?uncap_first}.id${r"}"}">Delete ${class.name?uncap_first}</a></td>
            </tr>
        </table>
    </div>
<#else>
</#if>
</body>
</html>