<!--
WARNING: This file was autogenerated by MagicDraw MBRS plugin.
Do not update it because if you run generator again you changes will be deleted
-->
<html>
<head>
    <style>
        ${r"<#include 'common.css'>"}
    </style>
</head>
<body>
<header>
    <h2>Generated application</h2>
</header>
<div class="wrapper">
    <ul>
        <#list allClasses as class>
            <li><a href="/${class.name?uncap_first}/all">See all ${class.name?uncap_first}s</a></li>
        </#list>
    </ul>
</div>
</body>
</html>