// WARNING: This file was autogenerated by MagicDraw MBRS plugin.
// Do not update it because if you run generator again you changes will be deleted

<#assign repositoryName="${class.name?uncap_first}Repository">
package ${class.typePackage};

import lombok.RequiredArgsConstructor;
import ${class.typePackage?keep_before(".")}.model.${class.name};
import ${class.typePackage?keep_before(".")}.repository.${class.name}Repository;
import org.springframework.stereotype.Service;

import java.util.List;
import java.lang.Exception;

@Service
@RequiredArgsConstructor
public class ${class.name}GenService {
<#if class.page??>
    private final ${class.name?cap_first}Repository ${repositoryName};

<#if class.page.details?c=="true" || class.page.update?c=="true">
    public ${class.name} findById(Long id) throws Exception {
        return ${repositoryName}.findById(id)
            .orElseThrow(() -> new Exception("${class.name?uncap_first}-not-found"));
    }

</#if>
<#if class.page.getAll?c=="true">
    public List<${class.name}> findAll() {
        return ${repositoryName}.findAll();
    }

</#if>
<#if class.page.create?c=="true" || class.page.update?c=="true">
    public ${class.name} save(${class.name} ${class.name?uncap_first}) {
        return ${repositoryName}.save(${class.name?uncap_first});
    }

    public void delete(${class.name} ${class.name?uncap_first}) {
        ${repositoryName}.delete(${class.name?uncap_first});
    }

</#if>
</#if>
}
